[package]
name = "ipsee"
description = "Dump network packet data"
version = "0.1.0"
authors = ["Eric Mrak <enmrak@gmail.com>"]

[dependencies]
pnet = "0.33.0"
clap = { version = "4.2.5", features = ["derive"] }
